# Model selection
[model]
architecture = "resnet50"

# Model hyperparameters per architecture
[model.resnet34]
lr=[0.1, 0.01, 0.001]
optimizer=["sgd", "adam"]
momentum=[0.9, 0.5]
epochs=[10, 20]

[model.resnet50]
lr=[0.01, 0.001]
optimizer=["sgd"]
momentum=[0.5, 0.0]
epochs=[10, 20]

[model.resnet101]
lr=[0.1]
optimizer=["adam"]
momentum=[0.5]

[model.resnet152]
lr=[0.01, 0.001]
optimizer=["sgd"]
momentum=[0.9]

# inference config
[inference]
batch_size = 4
limit = 32

# Training config
[training]
lr = 0.01
optimizer = "sgd"
momentum = 0.9
batch_size = 32
limit = 640
epochs = 2

# Tuning config
[tuning]
batch_size = [16, 32]
limit = 320

# General defaults
[defaults]
output_dir = "results"


