[data]
path = "data"
url = "https://archive.ics.uci.edu/static/public/352/online+retail.zip"
data_file = "data/retail.csv"
sample_file = "data/sample_retail.csv"
sample_size = 5000
random_state = 42

[sqlite]
schema = "retail"
db_path = "data/retail.db"
sql_path = "sql/schema.sql"

